name: Weaver Docker Generator
on:
  push:
    tags: [ '**' ]
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
env:
  TEST_WEAVER_TAG: otel/weaver:test
jobs:
  make-docker-image:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        images: otel/weaver
    - name: Build test image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
          push: false
          load: true
          tags: ${{ env.TEST_WEAVER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
    - name: Test
      run: |
          docker run --rm ${{ env.TEST_WEAVER_TAG }} --help
    - name: Log in to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        provenance: mode=max
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
