name: Weaver Docker Generator
on:
  push:
    tags: [ '**' ]
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/publish-docker.yml
      - 'src/**'
      - 'creates/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t weaver && docker run --rm weaver --help

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t weaver
    - name: Push the Docker image
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        function tag_and_push {
          docker tag weaver "otel/weaver:${1}" && docker push "otel/weaver:${1}"
        }
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          tag_and_push "latest"
        elif [[ "${GITHUB_REF}" =~ refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            TAG="${GITHUB_REF#"refs/tags/v"}"
            tag_and_push "${TAG}"
        else
          tag_and_push "${GITHUB_REF#"refs/tags/"}"
        fi
    - name: Push the Dev Docker image
      if: startsWith(github.ref, 'refs/heads/feature/')
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        function tag_and_push {
          docker tag weaver "otel/weaver:${1}" && docker push "otel/weaver:${1}"
        }
        TAG="${GITHUB_REF#"refs/heads/"}"
        TAG="${TAG/"/"/"-"}"
        tag_and_push "${TAG}"